### ISSUE TITLE
Cars views page ready for review

### ISSUE THREAD

**Issue by ak415** [aazaiez/Wheelio#2]

**Comment by s-pangburn** [comment]
Very solid job Akram! I already gave you my feedback, so here is a checklist just as a reminder:

- [x] Fix routing bug for Car Show
- [x] Adjust Flex properties for car details
- [x] Adjust image gallery to take up more of the screen

**Comment by ak415** [comment]
Thanks for the feedback! Bug fixed!

**Comment by s-pangburn** [comment]
Looks good! I'll mark this feature as complete! 👍
